### ISSUE TITLE
10.2-5.poker.c

### ISSUE THREAD

**Issue by alpha-beta-soup** [twcamper/c-programming#1]
Don't know if you're taking issues on this, but I just noticed that your poker hand program ([10.2-5.poker.c](https://github.com/twcamper/c-programming/blob/master/10/10.2-5.poker.c)) doesn't calculate a straight correctly. It inspects the hand, finding the maximum and minimum card ranks, and then checks if `max - min == 4`, and if so, declares a straight. [This](https://github.com/twcamper/c-programming/blob/master/10/10.2-5.poker.c#L126-L136) is incorrect, e.g. here is some offending input/output:

```
Enter a card: 2C 
Enter a card: 3C
Enter a card: 6C
Enter a card: 6S
Enter a card: 6H
Straight

```

I suppose the best way to assert this is to instead sort the hand based on rank, and then check that the sorted hand increases monotonically with respect to rank.

I've picked up a few tidbits from comparing your solutions to mine, so thought I'd just throw something back your way as thanks. Hopefully anyone else using the same resource will benefit :)

**Comment by twcamper** [comment]
Ah!  Unit tests would have been useful!  I'm glad my old source is helpful in your studies, and I'm glad people are still using Dr King's wonderful book.
